### ISSUE TITLE
Issue in Shield slider.

### ISSUE THREAD

**Issue by dcushen** [Year4-Games-Development/SBSP-A1-nav-combat#20]
When you turn shields off, I have tried to set the slider to inactive, sometimes the slider will disappear when you do this. Not quite sure why if anyone would like to have a look. 

![image](https://user-images.githubusercontent.com/23439688/32511740-9676cb6a-c3ec-11e7-9e97-2681268404e0.png)

After you mess with the slider this happens
![image](https://user-images.githubusercontent.com/23439688/32511756-a7a2158e-c3ec-11e7-9ed2-9a24c991d28e.png)

**Comment by w-riordan** [comment]
Instead of disabling the slider set Interactable to false should solve the issue.
https://docs.unity3d.com/ScriptReference/UI.Selectable-interactable.html

**Comment by dcushen** [comment]
Got it. Thanks!
